create table if not exists public."juniorAchievements" (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  class_id uuid not null references public.classes(id) on delete cascade,
  achievement_type text not null check (
    achievement_type in (
      'quiet',
      'reading',
      'speaking',
      'try',
      'vocabulary',
      'dictation',
      'participation',
      'grammar'
    )
  ),
  count integer not null default 0 check (count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, class_id, achievement_type)
);

create index if not exists junior_achievements_class_type_count_idx
on public."juniorAchievements" (class_id, achievement_type, count desc);

alter table public."juniorAchievements" enable row level security;

create or replace function public.get_student_junior_achievements(
  input_student_id uuid,
  input_class_id uuid
)
returns table (
  achievement_type text,
  achievement_count integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.students s
    join public.students_language sl
      on sl.student_id = s.id
    join public.classes c
      on c.id = sl.class_id
    join public.user_access ua
      on ua.user_id = s.user_id
    where s.id = input_student_id
      and sl.class_id = input_class_id
      and ua.auth_user_id = auth.uid()
      and upper(trim(c.name)) ~ '^(JA|JB|SA|SB)'
  ) then
    raise exception 'Student achievements are not available for this class'
      using errcode = '42501';
  end if;

  return query
  select
    achievements.achievement_type,
    achievements.count as achievement_count
  from public."juniorAchievements" achievements
  where achievements.student_id = input_student_id
    and achievements.class_id = input_class_id;
end;
$$;

grant execute on function public.get_student_junior_achievements(uuid, uuid)
to authenticated;

create or replace function public.get_junior_achievement_leaderboard(
  input_student_id uuid,
  input_class_id uuid
)
returns table (
  achievement_type text,
  student_id uuid,
  student_name text,
  achievement_count integer,
  rank_position bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.students s
    join public.students_language sl
      on sl.student_id = s.id
    join public.classes c
      on c.id = sl.class_id
    join public.user_access ua
      on ua.user_id = s.user_id
    where s.id = input_student_id
      and sl.class_id = input_class_id
      and ua.auth_user_id = auth.uid()
      and upper(trim(c.name)) ~ '^(JA|JB|SA|SB)'
  ) then
    raise exception 'Class achievement leaderboard is not available'
      using errcode = '42501';
  end if;

  return query
  with achievement_types(achievement_type) as (
    values
      ('quiet'::text),
      ('reading'::text),
      ('speaking'::text),
      ('try'::text),
      ('vocabulary'::text),
      ('dictation'::text),
      ('participation'::text),
      ('grammar'::text)
  ),
  enrolled_students as (
    select distinct s.id, s.name
    from public.students_language sl
    join public.students s
      on s.id = sl.student_id
    where sl.class_id = input_class_id
  ),
  scores as (
    select
      types.achievement_type,
      student.id as student_id,
      student.name as student_name,
      coalesce(achievements.count, 0)::integer as achievement_count
    from achievement_types types
    cross join enrolled_students student
    left join public."juniorAchievements" achievements
      on achievements.class_id = input_class_id
      and achievements.student_id = student.id
      and achievements.achievement_type = types.achievement_type
  )
  select
    scores.achievement_type,
    scores.student_id,
    scores.student_name,
    scores.achievement_count,
    dense_rank() over (
      partition by scores.achievement_type
      order by scores.achievement_count desc
    ) as rank_position
  from scores
  order by
    scores.achievement_type,
    scores.achievement_count desc,
    scores.student_name;
end;
$$;

grant execute on function public.get_junior_achievement_leaderboard(uuid, uuid)
to authenticated;

create or replace function public.award_junior_achievement(
  input_student_language_id uuid,
  input_achievement_type text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  target_student_id uuid;
  target_class_id uuid;
  new_count integer;
begin
  if input_achievement_type not in (
    'quiet',
    'reading',
    'speaking',
    'try',
    'vocabulary',
    'dictation',
    'participation',
    'grammar'
  ) then
    raise exception 'Unknown junior achievement type'
      using errcode = '22023';
  end if;

  select sl.student_id, sl.class_id
  into target_student_id, target_class_id
  from public.students_language sl
  join public.classes c
    on c.id = sl.class_id
  where sl.id = input_student_language_id
    and upper(trim(c.name)) ~ '^(JA|JB|SA|SB)'
    and public.teacher_can_access_class(sl.class_id);

  if target_student_id is null or target_class_id is null then
    raise exception 'Teacher cannot award this achievement'
      using errcode = '42501';
  end if;

  insert into public."juniorAchievements" as achievements (
    student_id,
    class_id,
    achievement_type,
    count
  )
  values (
    target_student_id,
    target_class_id,
    input_achievement_type,
    1
  )
  on conflict (student_id, class_id, achievement_type)
  do update set
    count = achievements.count + 1,
    updated_at = now()
  returning count into new_count;

  return new_count;
end;
$$;

grant execute on function public.award_junior_achievement(uuid, text)
to authenticated;
